; LAB 5 USE OF LIBRARY
; MACROS

INCLUDE "EMU8086.INC"

.MODEL SMALL
.STACK 100H
.DATA

.CODE
      MOV AX, @DATA
      MOV DS, AX
; WE WILL BE USING 4 MACROS
;PUTC, PRINT, PRINTN, GOTOXY

;PUTC CAN DISPLAY 8-BIT(1BYTE) CHARCATERS
      PUTC '1'     ;SINGLE KEY OUTPUT
      MOV BL, '5'
      PUTC BL     
      
      PRINTN
            
;PRINT, PRINTS STRING THAT IS STORED IN STACK
;NO NEED OF TERMINATING CHARACTER IN STRING
      PRINT "HELLO WORLD!"
      PRINTN "2021"
;PRINTN PRINTS STRING THEN A NEW LINE  

;GOTOXY,POSITIONS THE CURSOR IN A SPECIFIC CO-ORDIANTE
      GOTOXY 33, 12
      PRINT "ASSEMBLY CODE"
      
EXIT: 
      MOV AH, 4CH
      INT 21H             
