; LAB 5 USE OF LIBRARY
; PROCEDURES

INCLUDE "EMU8086.INC"

.MODEL SMALL
.STACK 100H
.DATA
      MSG DB "ENTER TWO NUMBERS: ", 0 ;NULL
      ;0 IS THE TERMINATING CHARACTER HERE
.CODE
      MOV AX, @DATA
      MOV DS, AX

;CALL IS USED TO CALL PROCEDURES
;WE NEED TO DEFINE PROCEDURES AFTER EXIT
;PRINT_STRING IS USED TO PRINT STRING

      LEA SI, MSG
     ;LOAD OFFSET OF MSG IN SI
     ;NO OTHER REGISTERS CAN BE USED
      CALL PRINT_STRING
      PRINTN  
      
;SCAN_NUM IS USED TO INPUT NUMBER IN CX
;DATA SIZE - WORD, TYPE - DECIMAL
      CALL SCAN_NUM
      MOV AX, CX
      PRINTN
      
      CALL SCAN_NUM
      MOV BX, CX 
      PRINTN
      
      SUB AX, BX
      PRINT "SUBTRACTION RESULT: "
      CALL PRINT_NUM
;PRINT_NUM PRINTS THE NUMBER,THAT IS IN AX
           
EXIT: 
      MOV AH, 4CH
      INT 21H             

DEFINE_PRINT_STRING  
DEFINE_SCAN_NUM
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS