;LOGIC INSTRUCIONS
;ALL LOGIC INSTRUCTIONS AFFECT THE FLAG

INCLUDE "EMU8086.INC"

.MODEL SMALL
.STACK 100H
.DATA
.CODE
      ;AND - CLEAR OPERATION
;CHECK EVEN ODD
      CALL SCAN_NUM
      PRINTN
      
      MOV AX, 1
      AND AX, CX
      CMP AX, 0
      JE PRINT_EVEN
      PRINTN "ODD"
      JMP EXIT
      
PRINT_EVEN:
      PRINTN "EVEN"      
      
EXIT:
      MOV AH, 4CH
      INT 21H      

DEFINE_SCAN_NUM
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS