
; LAB 3 ARRAY    
.MODEL SMALL
.STACK 100H
.DATA 
     ;DECLARATION IS SAME AS VARIABLE  
     ARRAY1 DB 61H, 45H, ?, ?, ? ; ARRAY SIZE 5
     ; ? - BLANK SPACE
     ; ELEMENTS ARE ACCESSED BY INDEX  
     ARRAY2 DW 10 DUP('A', 10H, 5H)
     ; ARRAY2 SIZE = 10 * 3 = 30 
     ; DUP - DUPLICATES AS - A, 10H, 5H, A, 10H, 5H
     
.CODE 
     MOV AX, @DATA
     MOV DS, AX
     
     ;ARRAY ELEMENT ACCESSING BY INDEX
     MOV AL, ARRAY1 ; ARRAY1 POINTS THE 1ST ELEMENT
     MOV BL, ARRAY1[1]
     MOV CL, ARRAY1[2] ; [BX],[SI],[DI],[BP] CAN BE USED 
     
INPUT: ;TAKING INPUT AND PUT IT IN THE ARRAY INDEX
     ; WE WILL USE INDEX REGISTER SI HERE
     MOV SI, 1H
     MOV AH, 1H
     
     ;INPUT - ARRAY ELEMENTS
     INT 21H  
     MOV ARRAY1[SI+2], AL ; 1+2 = 3RD INDEX 
     INT 21H
     MOV ARRAY1[SI+3], AL
     INT 21H
     MOV ARRAY1[SI+4], AL ;WE CAN USE 'INC SI' AS WELL
     
OUTPUT: 
     ;PRINTING IN REVERSE
     MOV AH, 2H
     MOV DL, 0AH
     INT 21H
     
     MOV DL, ARRAY1[SI+4]
     INT 21H
     MOV DL, ARRAY1[SI+3]
     INT 21H  
     MOV DL, ARRAY1[SI+2]
     INT 21H  
     
EXIT: ; EXIT FUNCTION
     MOV AH, 4CH
     INT 21H  