; LAB 2

; DIRECTIVES 
.MODEL SMALL 
; MODEL DIRECTIVE TELLS THE ASSEMBLER ABOUT THE SIZE
; OF THE PROGRAM - SMALL : 1 CODE & 1 DATA SEGMENT MEMEORY
; WHAT WILL BE THE SIZE OF THE MEMORY

.STACK 100H ; 100H - SIZE OF OFFSET ADDRESS
; WE CAN USE 000H - 100H 

.DATA
; DATA SEGMENT 

.CODE
; CODE SEGMENT     
MOV CX, 1234H 

; INPUT LABEL   
INPUT:     
MOV AH, 1H ; 1H - SINGLE KEY INPUT FUNCTION  
INT 21H    ; INPUT VALUE IS STORED IN AL REGISTER
MOV BL, AL ; MOVING THE INPUT VALUE TO ANOTHER REGISTER

ADD AL, 2  ; ADDS 2 WITH INPUT CHARACTER   

;TAKING ANOTHER INPUT
MOV AH, 1H 
INT 21H   
MOV BH, AL ; MOVING THE INPUT VALUE TO ANOTHER REGISTER  


; OUTPUT  FROM DL REGISTER   
OUTPUT: 
; NEW LINE 
MOV AH, 2H
MOV DL, 0AH ; 0AH - NEW LINE 
INT 21H
MOV DL, 0DH ; 0DH - CARRIAGE RETURN
INT 21H

MOV DL, BL ; THE CHARACTER THAT WE WANT TO SHOW AS OUTPUT,
MOV AH, 2H ; MUST HAVE TO BE IN DL REGISTER
INT 21H     

; SPACE
MOV DL, 20H ; 20H - SPACE
INT 21H
                               

MOV DL, BH ; SIMPLE MOVE OPERATION
MOV AH, 2H ; 2H - SINGLE KEY OUTPUT FUNCTION
INT 21H

          
; EXIT FUNCTION 
EXIT:           
MOV AH, 4CH
; 4CH - A TERMINATING FUNCTION / DOS EXIT FUNCTION

INT 21H ; INTERRUPT - REQUESTS PROCESSOR TO EXECUTE 
; A SPECIAL FUNCTION,
; INTERRUPT ROUTINE IDENTIFIES DIFFERENT FUNCTIONS
; 21H - EXECUTE DOS(DISK OPERATING SYSTEM) FUNCTION
; FUNCTION NUMBER - FUNCTION IDENTIFICATION => AH  

; WHICH FUNCTION? ASSEMBLER CHECKS AH REGISTER TO KNOW THAT