
;LAB 4 - CONDITIONAL JUMP
;ALTERNATE OF LOOP
.MODEL SMALL
.STACK 100H
.DATA
.CODE  

      MOV AX, @DATA
      MOV DS, AX
      
      MOV CX, 5H
      MOV AH, 2H
      MOV DL, 30H ;DIGIT- 0 

DISPLAY:
      INT 21H
      INC DL
      DEC CX     ;DECREASING CX MANUALLY
JNZ DISPLAY      ;JNZ - JUMP IF NOT ZERO 
;CHECKS ZF == 0
;IF YES, GO TO NEXT INSTRUCTION
;IF NO, GO TO LABEL
;WHEN CX IS 0, THE VALUE OF ZERO FLAG IS 1
;JNZ IS USED BASED ON THE STATUS OF FLAG REGISTER 

;JZ - JUMP IS ZERO 
;CHECKS ZF == 1
;IF YES, GO TO NEXT INSTRUCTION
;IF NO, GO TO LABEL

EXIT:
      MOV AH, 4CH
      INT 21H 

