
;LAB 4 - FLOW CONTROL INSTRUCTIONS 
;JMP INSTRUCTION

.MODEL SMALL
.STACK 100H
.DATA

.CODE
      MOV AX, @DATA
      MOV DS, AX 

DISPLAY: ;LABEL      
      MOV AH, 2   ;JUMPS HERE
      MOV DL, 30H
      INT 21H
JMP DISPLAY       ;WORKS SAME AS GOTO LABEL IN C
                  ;JUMPS INTO THE LABEL UNCONDITIONALLY 
;ANY LABEL NAME IS FINE- SHOULD NOT BE THE IMMIDIATE LABEL
;IT BECOMES AN INFINITE LOOP   

      MOV DL, 5
      INT 21H
;THESE INSTRUCTIONS WILL NOT BE EXECUTED
EXIT:
      MOV AH, 4CH
      INT 21H