
;LAB 4 - FLOW CONTROL INSTRUCTIONS 
;LOOP

.MODEL SMALL
.STACK 100H
.DATA
      ARRAY DB "ENDS$"
.CODE
      MOV AX, @DATA
      MOV DS, AX 

;BEFORE USING LOOP, FIX NUMBER OF COUNTS IN CX REGISTER 
      MOV CX, 5H   ;LOOP WILL ITERATE 5 TIMES
            
DISPLAY:          ;LABEL      
      MOV AH, 2H   ;JUMPS HERE
      MOV DL, 30H
      INT 21H
LOOP DISPLAY    ;JUMPS INTO THE LABEL BUT NOT INFINITE TIMES
;FIRST IT DECREASES CX, THEN CHECKS IF CX == 0 
;IF CX != 0, THEN GO TO LABEL 
;IF CX == 0, THEN GO TO THE NEXT INSTRUCTION

      LEA DX, ARRAY 
      MOV AH, 9H
      INT 21H   ;PRINTS ENDS

EXIT:
      MOV AH, 4CH
      INT 21H